# Generated by Django 2.2.3 on 2022-01-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20220105_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_of_following', to='network.Post')),
            ],
        ),
    ]
