# Generated by Django 2.2.3 on 2022-01-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_following',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
