# Generated by Django 2.2.3 on 2022-01-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20220106_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_following',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
