# Generated by Django 2.2.3 on 2022-02-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20220126_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.CharField(default='no', max_length=200, null=True),
        ),
    ]
