# Generated by Django 2.2.3 on 2022-02-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
    ]
