# Generated by Django 2.2.3 on 2022-02-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20220202_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.CharField(default='no', max_length=200, null=True),
        ),
    ]
