# Generated by Django 2.2.3 on 2022-02-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20220202_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(related_name='posts_liked', to='network.Post'),
        ),
    ]
