# Generated by Django 2.2.3 on 2022-02-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_users_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_following',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
