# Generated by Django 2.2.3 on 2022-02-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_users_following_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_Following',
            new_name='User_Following',
        ),
    ]
