# Generated by Django 2.2.3 on 2021-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='listing_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
