# Generated by Django 2.2.3 on 2021-11-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_watchlist_listing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('starting_bid', models.CharField(max_length=30)),
            ],
        ),
    ]
