# Generated by Django 2.2.3 on 2021-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
