# Generated by Django 2.2.3 on 2021-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
