# Generated by Django 2.2.3 on 2021-11-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
