# Generated by Django 2.2.3 on 2021-11-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_inactive_listng'),
    ]

    operations = [
        migrations.AddField(
            model_name='inactive_listng',
            name='winning_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
