# Generated by Django 2.2.3 on 2021-11-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_inactive_listng_winning_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactive_listng',
            name='starting_bid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inactive_listng',
            name='winning_bid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
