# Generated by Django 2.2.3 on 2021-11-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20211129_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactive_listng',
            name='starting_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inactive_listng',
            name='winning_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
