# Generated by Django 2.2.3 on 2021-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
