# Generated by Django 2.2.3 on 2021-11-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20211129_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
