# Generated by Django 2.2.3 on 2021-11-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20211130_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactive_listng',
            name='winning_bid',
            field=models.IntegerField(null=True),
        ),
    ]
