# Generated by Django 2.2.3 on 2021-11-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20211130_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
