# Generated by Django 2.2.3 on 2021-11-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_listing_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='listing_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
