# Generated by Django 2.2.3 on 2021-11-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20211130_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='listing_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
